spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: root
    password: 20010528ok
  sql:
    init:
      mode: never

app:
  security:
    admin:
      username: admin
      password: 20010528ok
